language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mfERK5rKBENfAZXWkh5GhGv2vhesIQOoznPKoSVto5ObIMxik79GIl3hBC4AoG9M8YsfE7zJ5fuM03qm1f6r6d8Wr+3FsYDgxAj3leglQYJ6+4B8i2AqIpEqJ1subwWijwMAaNRgV10K/sq7KyngD+vtG05y2FhuS76mY4kljEvLa9dvn5b0MoV21LLwFL+t2ndtrP5pXafxX+5hm3dUwY1nxp4cnRjiMFN86CvNtMgUcGp67EuaSLyJehWojQF2UM1WZN8gYbWHCqWwRCXetSTRFoosuG6k6KglGGJr8uy1zw5V6761Jhyjqi+AFj9yWc/w8cOm9QMYNakhxYaQbk5JvN2s2Zxjp6BazUiakzLX1vVxAEgYJxeEzj1pA21Etii0ifFY75GDktxShxXUzVrgMe1iINGg2qRoqC/9m7g15t5NCvWZJ24seg3gR0kUd8YElYdBnxc+Rw1vtLTpGtfHJPhJkjZrrNKbpSb6rX00Qv/5Dq/fNgpdhY5EuO7rujk9/ej64AuQMB0YW1lhboeTk2irsh7D3R9zNG7ORVJ1Kd+ls/SXKCYLIu4egbW6OQpoOHXMuyTJnm553s9QbAEwvYapvlsKjGx/nGwXczuxmqA3ig1z6pZiUtFhnoBAomceLoOyaKcH+5Lt0vsJ81ZwNDxZCyi6qkPdVrnVNgI=
  app: nameless-retreat-44933
  on:
    repo: sretundijr/blog-api
